//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace home_accounting.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class homeaccountEntities : DbContext
    {
        private static homeaccountEntities home;
        public homeaccountEntities()
            : base("name=homeaccountEntities")
        {
        }

        public static homeaccountEntities context()
        {
            if(home == null)
            {
                home = new homeaccountEntities();
            }
            return home;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accounting> accounting { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<category_type> category_type { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
